web:
  image: node:latest
  ports:
    - "5000:5000"
  volumes:
    - ./:/app/
  working_dir: /app
  command: npm start
  environment:
    - DEBUG=express:router
    - PORT=5000
  links:
    - redis
redis:
  image: redis
